/** 멤버십 서비스에 필요한 기초 테이블 스크립트 **/


/* 1.회원 정보 */
CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT NOT NULL AUTO_INCREMENT,
    ACCOUNT_NM VARCHAR(50) NOT NULL,
    STATUS CHAR DEFAULT '1',
    EMAIL VARCHAR(40) NOT NULL,
    BIRTH VARCHAR(8) NOT NULL,
    HPHONE VARCHAR(11) NOT NULL,
    GRADE VARCHAR(10) DEFAULT 'USER',
    INSERT_DATE TIMESTAMP NOT NULL,
    INSERT_USER BIGINT NOT NULL,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,

    PRIMARY KEY (ACCOUNT_ID)
);

/* 2.가맹점 정보 */
CREATE TABLE FRANCHISEE (
    FRANCHISEE_ID BIGINT NOT NULL AUTO_INCREMENT,
    FRANCHISEE_NM VARCHAR(200) NOT NULL,
    STATUS CHAR DEFAULT '1',
    TEL_NO VARCHAR(20),
    ZIP_CD VARCHAR(5),
    ADDR1 VARCHAR(200),
    ADDR2 VARCHAR(200),
    FRANCHISEE_MNG_NM VARCHAR(50),
    FRANCHISEE_MNG_HPHONE VARCHAR(11),
    FRANCHISEE_MNG_EMAIL VARCHAR(40),
    BIGO VARCHAR(2000),
    INSERT_DATE TIMESTAMP NOT NULL,
    INSERT_USER BIGINT NOT NULL,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,

    PRIMARY KEY (FRANCHISEE_ID)
);

/* 3.멤버십 정보 */
CREATE TABLE MEMBERSHIP (
    MSP_ID BIGINT NOT NULL AUTO_INCREMENT,
    MSP_NM VARCHAR(200) NOT NULL,
    STATUS CHAR DEFAULT '1',
    MSP_INFO VARCHAR(200),
    MSP_IMG_URL VARCHAR(300),
    HOMEPAGE_URL VARCHAR(100),
    MSP_ACCUM_FG CHAR DEFAULT '2',
    MSP_ACCUM_AMT INT DEFAULT 0,
    MSP_ACCUM_RAT INT DEFAULT 10,
    MSP_ACCUM_MIN_AMT INT DEFAULT 0,
    MSP_POINT_EXPIRE_DAYS INT DEFAULT 0,
    BIGO VARCHAR(2000),
    INSERT_DATE TIMESTAMP NOT NULL,
    INSERT_USER BIGINT NOT NULL,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,

    PRIMARY KEY (MSP_ID)
);

/* 4.멤버십별 가입가능한 회원등급 */
CREATE TABLE MEMBERSHIP_GRADE (
    MSP_ID BIGINT NOT NULL,
    ACCOUNT_GRADE VARCHAR(10) NOT NULL,
    STATUS CHAR DEFAULT '1',
    INSERT_DATE TIMESTAMP NOT NULL,
    INSERT_USER BIGINT NOT NULL,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT
);
ALTER TABLE MEMBERSHIP_GRADE ADD PRIMARY KEY(MSP_ID, ACCOUNT_GRADE);

/* 5.멤버십별 가맹점 */
CREATE TABLE MEMBERSHIP_FRANCHISEE (
    MSP_ID BIGINT NOT NULL,
    FRANCHISEE_ID BIGINT NOT NULL,
    STATUS CHAR DEFAULT '1',
    INSERT_DATE TIMESTAMP NOT NULL,
    INSERT_USER BIGINT NOT NULL,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT
);
ALTER TABLE MEMBERSHIP_FRANCHISEE ADD PRIMARY KEY(MSP_ID, FRANCHISEE_ID);