-- ACCOUNT 초기 데이터 셋팅
INSERT INTO ACCOUNT (ACCOUNT_NM, STATUS, EMAIL, BIRTH, HPHONE, GRADE, INSERT_DATE, INSERT_USER)
    VALUES ('홍길동', '1', 'gdhong@naver.com', '19900505', '01011112222', 'USER', SYSDATE, 'ADMIN');