/** 멤버십 서비스에 필요한 기초 테이블 스크립트 **/


/* 1.회원 정보 */
CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT NOT NULL AUTO_INCREMENT,
    ACCOUNT_NM VARCHAR(50) NOT NULL,
    STATUS CHAR DEFAULT '1',
    EMAIL VARCHAR(40) NOT NULL,
    BIRTH VARCHAR(8) NOT NULL,
    HPHONE VARCHAR(11) NOT NULL,
    GRADE VARCHAR(10) DEFAULT 'USER',
    INSERT_DATE TIMESTAMP,
    INSERT_USER BIGINT,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '회원정보';

/* 2.가맹점 정보 */
CREATE TABLE FRANCHISEE (
    FRANCHISEE_ID BIGINT NOT NULL AUTO_INCREMENT,
    FRANCHISEE_NM VARCHAR(200) NOT NULL,
    STATUS CHAR DEFAULT '1',
    TEL_NO VARCHAR(20),
    ZIP_CD VARCHAR(5),
    ADDR1 VARCHAR(200),
    ADDR2 VARCHAR(200),
    FRANCHISEE_MNG_NM VARCHAR(50),
    FRANCHISEE_MNG_HPHONE VARCHAR(11),
    FRANCHISEE_MNG_EMAIL VARCHAR(40),
    BIGO VARCHAR(2000),
    INSERT_DATE TIMESTAMP,
    INSERT_USER BIGINT,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,
    CONSTRAINT FRANCHISEE_PK PRIMARY KEY(FRANCHISEE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '가맹점정보';

/* 3.멤버십 정보 */
CREATE TABLE MEMBERSHIP (
    MSP_ID BIGINT NOT NULL AUTO_INCREMENT,
    MSP_NM VARCHAR(200) NOT NULL,
    STATUS CHAR DEFAULT '1',
    MSP_INFO VARCHAR(200),
    MSP_IMG_URL VARCHAR(300),
    HOMEPAGE_URL VARCHAR(100),
    MSP_ACCUM_FG CHAR DEFAULT '2',
    MSP_ACCUM_AMT INT DEFAULT 0,
    MSP_ACCUM_RAT INT DEFAULT 10,
    MSP_ACCUM_MIN_AMT INT DEFAULT 0,
    MSP_POINT_EXPIRE_DAYS INT DEFAULT 0,
    BIGO VARCHAR(2000),
    INSERT_DATE TIMESTAMP,
    INSERT_USER BIGINT,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,
    CONSTRAINT MEMBERSHIP_PK PRIMARY KEY(MSP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십정보';

/* 4.멤버십별 가입가능한 회원등급 */
CREATE TABLE MEMBERSHIP_GRADE (
    MSP_ID BIGINT NOT NULL,
    ACCOUNT_GRADE VARCHAR(10) NOT NULL,
    STATUS CHAR DEFAULT '1',
    INSERT_DATE TIMESTAMP,
    INSERT_USER BIGINT,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,
    CONSTRAINT MEMBERSHIP_GRADE_PK PRIMARY KEY(MSP_ID, ACCOUNT_GRADE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십별 가입가능한 회원등급';

/* 5.멤버십별 가맹점 */
CREATE TABLE MEMBERSHIP_FRANCHISEE (
    MSP_ID BIGINT NOT NULL,
    FRANCHISEE_ID BIGINT NOT NULL,
    STATUS CHAR DEFAULT '1',
    INSERT_DATE TIMESTAMP,
    INSERT_USER BIGINT,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,
    CONSTRAINT MEMBERSHIP_FRANCHISEE_PK PRIMARY KEY(MSP_ID, FRANCHISEE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십별 가맹점';

/* 6.회원별 멤버십 가입정보 */
CREATE TABLE MY_MEMBERSHIP (
    ACCOUNT_ID BIGINT NOT NULL,
    MSP_ID BIGINT NOT NULL,
    STATUS CHAR DEFAULT '1',
    TOTAL_AMT INT NOT NULL,
    USABLE_POINT INT NOT NULL,
    WITHDRAWAL_DATE TIMESTAMP,
    INSERT_DATE TIMESTAMP,
    INSERT_USER BIGINT,
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER BIGINT,
    CONSTRAINT MY_MEMBERSHIP_PK PRIMARY KEY(ACCOUNT_ID, MSP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '회원별 멤버십 가입정보';

/* 7.나의 멤버십_적립내역 */
CREATE TABLE MY_MEMBERSHIP_ACCUM (
    POINT_ACCUM_SEQ VARCHAR(20) NOT NULL,
    MSP_ID BIGINT NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    FRANCHISEE_ID BIGINT NOT NULL,
    ACCUM_FG CHAR DEFAULT 'A',
    TRADE_POINT INT NOT NULL,
    EXPIRE_YMD VARCHAR(8) NOT NULL,
    CONSTRAINT MY_MEMBERSHIP_ACCUM_PK PRIMARY KEY(POINT_ACCUM_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '나의 멤버십_적립내역';

/* 8.나의 멤버십_적립 바코드 관리 */
CREATE TABLE MY_MEMBERSHIP_BARCODE (
    BAR_CD VARCHAR(50) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    MSP_ID BIGINT NOT NULL,
    FRANCHISEE_ID BIGINT,
    ACCUM_FG CHAR DEFAULT 'A',
    TRADE_AMT INT NOT NULL,
    USE_POINT INT NOT NULL,
    EXPIRE_DATE TIMESTAMP NOT NULL,
    USE_DATE TIMESTAMP,
    CONSTRAINT MY_MEMBERSHIP_BARCODE_PK PRIMARY KEY(BAR_CD, CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '나의 멤버십_적립 바코드 관리';


/* [시퀀스] - 멤버십바코드번호 */
CREATE SEQUENCE MY_MEMBERSHIP_BARCODE_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
CYCLE
NOCACHE;

/* [함수] - 멤버십바코드번호 채번
CREATE FUNCTION `F_GET_MY_MEMBERSHIP_BARCODE_NO` (
	P_ACCOUNT_NO BIGINT,
	P_SERVICE_FG VARCHAR(2)
) RETURNS VARCHAR(18)
BEGIN
	DECLARE V_HPHONE VARCHAR(11);
	DECLARE V_RANDOM_N0 VARCHAR(10);
	DECLARE V_CHECK_DIGIT VARCHAR(1);
	DECLARE V_BARCODE_NO VARCHAR(18);


	SELECT HPHONE
	       INTO V_HPHONE;
	  FROM ACCOUNT
	 WHERE ACCOUNT_NO = P_ACCOUNT_NO
	   AND STATUS = '1';

	SET V_RANDOM_N0 = TRIM(TO_CHAR(SYSTIMESTAMP, 'D'))
			|| TRIM( TO_CHAR( TO_CHAR(SYSTIMESTAMP, 'HH')*60*60 + TO_CHAR(SYSTIMESTAMP, 'MM')*60 + TO_CHAR(SYSTIMESTAMP, 'SS') , '00000' ) )
			|| TRIM(TO_CHAR(MY_MEMBERSHIP_BARCODE_SEQ.NEXTVAL, '0000'));

	SET V_CHECK_DIGIT = TO_CHAR(MOD(
					)TO_NUMBER(SUBSTR(V_RANDOM_N0, 1,1)) + TO_NUMBER(SUBSTR(V_RANDOM_N0, 2,1)) + TO_NUMBER(SUBSTR(V_RANDOM_N0, 3,1)) +
					TO_NUMBER(SUBSTR(V_RANDOM_N0, 4,1)) + TO_NUMBER(SUBSTR(V_RANDOM_N0, 5,1)) + TO_NUMBER(SUBSTR(V_RANDOM_N0, 6,1)) +
					TO_NUMBER(SUBSTR(V_RANDOM_N0, 7,1)) + TO_NUMBER(SUBSTR(V_RANDOM_N0, 8,1)) + TO_NUMBER(SUBSTR(V_RANDOM_N0, 9,1)) +
					TO_NUMBER(SUBSTR(V_RANDOM_N0, 10,1))) * 3406
			,9 ));

	SET V_BARCODE_NO = '88' ||SUBSTR(V_HPHONE,-2) || '1' || V_RANDOM_N0 || NVL(P_SERVICE_FG, '00') || V_CHECK_DIGIT;


	RETURN V_BARCODE_NO;
END;
*/